# Практическое занятие: Постановка задачи распознавания. Основы теории распознавания образов

Темы занятия:
- постановка задачи распознавания образов (объекты, классы, функция распознавания);
- различие между данными и знаниями, понятие гипотезы и закономерности;
- признаки и их роль в распознавании;
        - пример с сетевыми данными.

## Задача 1. От «сырых данных» к постановке задачи распознавания

**Условие.**
Рассмотрите три сценария:
1. Система проверки банковских транзакций на мошенничество.
2. Классификация входящих писем как «спам / не спам».
3. Распознавание дефектных изделий по фотографиям на конвейере.

### Требуется для каждого сценария:
1. Явно сформулировать задачу распознавания: указать множество объектов, множество классов, тип задачи (классификация / обнаружение аномалий / др.).
2. Разделить описание на:
   - **данные** (что измеряем/получаем от сенсоров/логов);
   - **знания** (априорные правила, предметная область, экспертные сведения);
   - **гипотеза** (что предполагаем о связи между данными и классами);
   - **закономерность** (какую зависимость хотим выявить: вероятностную, логическую, геометрическую и т.п.).
3. Описать, какие ошибки распознавания важнее в каждом случае (ложное срабатывание vs пропуск).

### Ваше решение задачи 1

_Заполните для каждого сценария:_
- множество объектов;
- множество классов;
- тип задачи;
- данные / знания / гипотеза / закономерность;
- приоритетные типы ошибок.

#### Система проверки банковских транзакций
 - Множество объектов: профили отправителя и получателя (их истории транзакций / статус), транзакция - сумма и дата
 - Множество классов: мошенническая, не мошенническая 
 - Тип задачи: бинарная классификация
 - Данные: Дата, сумма, тип, геопозиция, статистика транзакций пользователей, их статусы и устройства.
 - Знания: Паттерны поведения злоумышленников, эксперные оценки операторов
 - Гипотеза: Предполагается, что в поведении мошенников есть паттерны
 - Закономерность: Статистическая закономерность в имеющихся данных о пользователях и транзакциях, которая позволит по признаковым показаням транзакции позволят определить вероятность того, что она мошенническая 
 - Приоритетный тип ошибки: Ложно-отрицательные

#### Классификация входящих писем как «спам / не спам»
 - Множество объектов: Электронные письма
 - Множество классов: Спам / не спам
 - Тип задачи: бинарная классификация
 - Данные: Заголовок, отправитель, список получателей, тема, текст сообщения, вложение, ссылки, список "отмечено как спам"
 - Знания: База отправителей - спамеров,  база спам сообщений и вредоносных ссылок, база официальных интернет-магазинов / банков и т.п.
 - Гипотеза: В структуре отправляемых спам-сообщений, в тексте, ссылках и прикрепляемых файлах есть часто повторяющиеся паттерны
 - Закономерность: В спам сообщенях часто фигурируют одни и те же темы, например: перейдите по ссылке, откройте документ, и они позволяют определить спам.
 - Приоритетный тип ошибки: Важно как отобразить все нормальные сообщения и отсеять спам.

#### Распознавание дефектных изделий по фотографиям на конвейере
 - Множество объектов: Фото
 - Множество классов: Норма и брак
 - Тип задачи: Выявление аномалий 
 - Данные: Нынешнее фото, фото нормальных деталей, фото бракованного изделия
 - Знания: Экспертные сведения о возможных критических браках и их локализации по фото
 - Гипотеза: Бракованное изделие будет визуально отличаться по фото
 - Закономерность: Внешний вид критических областей совпадает у нормальных деталей, и отличается у бракованных
 - Приоритетный тип ошибки: Нахождение бракованных деталей

## Задача 2. Формализация задачи классификации в терминах $X, Y, f$

**Условие.**
Задача: автоматическое определение языка короткого текстового сообщения (русский, английский, китайский).

### Требуется:
1. Определить:
   - пространство объектов $X$ (что является наблюдаемыми данными);
   - множество меток классов $Y$;
   - вид функции распознавания $f: X \to Y$.
2. Сформулировать условие «правильного» распознавания в виде:
   
   $\forall (x,y)\in \mathcal{D}:\ f(x) \approx y$,
   
   где $\mathcal{D}$ — распределение пар «текст–язык».
3. Обсудить, какие априорные знания о языках можно использовать.

### Ваше решение задачи 2

_Опишите здесь X, Y, f и используемые знания._

X - набор коротких сообщений  
x - конкретный короткий текст  
Y - метки трёх классов по языкам.  
y - вектор вероятностей принадлежности к классам  
$$f: X \to Y$$
f - это алгоритм, который по векторному представлению сообщения определяет язык на котором оно написано. 


Условие качества - минимизация ошибки определения языка. 
$$min~P(f(x) \ne y) \text{ на распределении } \mathcal{D}$$
  
Какие знания необходимы:  
* Алфавиты языков
* Словари языков для составления токенов
* Специфические символы, характерные для разных языков

## Задача 3. Выделение признаков: оценка вариантов

**Условие.**
Задача: распознавание рукописных цифр (0–9).

Рассматриваются два набора признаков:
- Вариант A: один признак — количество чёрных пикселей в изображении.
- Вариант B: 4 признака —
  1. число пересечений средней горизонтальной линии с чёрными пикселями;
  2. число пересечений средней вертикальной линии;
  3. наличие замкнутого контура;
  4. отношение ширины к высоте цифры.

### Требуется:
1. Оценить, является ли каждый вариант разумным.
2. Для каждого варианта привести примеры цифр, которые могут плохо различаться.
3. Сформулировать общие требования к хорошему признаковому описанию.

### Ваше решение задачи 3

_Сравните варианты A и B и сформулируйте требования к признакам._

### А 
1. Вариант не разумный 
2. Разные цифры могут быть одного размера, одни и те же могут отличаться из раза в раз.
### B
1. Вариант может быть разумным, если:  
    1. Используется один характерный почерк
    2. В почерке нет завитков и помарок
    3. Символы отцентрованы и повернуты правильным образом
    4. Линии доводятся до конца (круги замыкаются, а "хвостики не теряются")
    5. Качество сканов приемлемое
2. Примеры неправильно считываемых цифр:
    1. Числа могут быть неправильно распознаны по п1 и п2 если они плохо отцентрованы или повернуты
    2. Числа с "завитыми хвостиками" могут отличаться
    3. 4 как ч может не считаться, и наоборот в случае с 1, 7
    4. 6 и 9 с неправильно повернутыми "хвостиками" могут выглядетиь похожими на 0
### Общие требования:
1. Система должна быть устойчива к уклону и деформациям чисел 
2. Должна следовать общей тенденции написания числа, а не строгому критерию полноты (например незаконченные круги и 1 без черты)
3. Мелкие неточности должны игнорироваться в угоду общей картины. (Хвостики не делают 8 из 6)
4. Экономность вычислений

## Задача 4. Данные vs знания: два подхода к спаму

**Условие.**
Задача: распознавание спама.

Подход 1 (данные): обучаем модель на большом датасете писем (статистический, ML-подход).
Подход 2 (знания): набор экспертных правил (rule-based).

### Требуется:
1. Для каждого подхода разделить «данные» и «знания».
2. Объяснить, чем отличается обучаемая закономерность от заданных вручную правил.
3. Привести примеры гипотез для каждого подхода.

### Ваше решение задачи 4

_Опишите данные, знания, гипотезы и закономерности для обоих подходов._

### ML подход 
Данные: размеченный датасет писем <br>
Знания: архитектура модели классификации, методы предобработки, спопобы построения эмбеддингов  <br>
Пример гипотезы: Предполагаем статистическую закономерность в текстах спам-сообщений, которую будем выявлять из эмбедднгов соощений  
### экспертный подход   
Данные: атрибуты писем <br>
Знания: Правила созданные экспертом <br>
Пример гипотезы: Экспертные знания о структурах и особенностях спам сообщений позволяют надежно определять характер каждого письма.
### В чем разница?
ML подход позволяет выявлять более неявные закономерности \ признаки в текстах спам писем. С другой строны, экспертный подход лучше интерпретируется, но дороже \ сложней в разработке, и поддержке.

## Задача 5. От закономерности к гипотезе

**Условие.**
Наблюдение: «Если нагрузка на сервер превышает 80% и температура ЦП выше 75°C, вероятность отказа в течение часа резко возрастает».

### Требуется:
1. Переформулировать наблюдение как гипотезу распознавания (классы: "скоро откажет" / "не откажет").
2. Описать необходимые данные для проверки гипотезы.
3. Предложить один или два признака, отражающих эту закономерность.

### Ваше решение задачи 5

_Запишите здесь гипотезу, данные и признаки._

Гипотеза:  
Если Нагрузка N > 0.8 & Температрура T > 75, то класс "скоро откажет", иначе "не откажет"  

Необходимые данные:  
Логи с указанием N и T, и последующим статусом сервера  

$$\text{Бинарный вариант результирующего признака: }[(N > 0.8) ~\&~ (T>75)]$$
$$\text{Непрерывный вариант результирующего признака: }N * (T - 20)/50$$

## Задача 6. Конструирование признаков из сетевых данных

**Условие.**
Рассмотрим фрагменты сетевого трафика с полями:
- `src_port`, `dst_port`, `protocol`, `packet_size_mean`, `packet_rate`, `label` (normal / attack).

### Требуется:
1. Предложить минимум 3 новых признака, которые помогают отличать normal от attack.
2. Объяснить для каждого признака, какую гипотезу о закономерности он отражает.
3. Классифицировать признаки по типу (числовой/категориальный, низкоуровневый/высокоуровневый).

In [1]:
import pandas as pd
import numpy as np

data = {
    'src_port': [8080, 3389, 80, 21, 21, 21, 443, 21, 3389, 22, 8080, 80],
    'dst_port': [80, 8080, 22, 443, 80, 443, 3389, 443, 3389, 80, 443, 8080],
    'protocol': ['TCP', 'UDP', 'UDP', 'UDP', 'UDP', 'UDP', 'TCP', 'UDP', 'TCP', 'TCP', 'TCP', 'UDP'],
    'packet_size_mean': [117, 598, 630, 389, 840, 282, 507, 472, 730, 720, 523, 557],
    'packet_rate': [22.3, 28.7, 59.8, 3.1, 54.9, 55.5, 11.8, 6.9, 18.9, 22.6, 42.2, 28.9],
    'label': ['attack', 'normal', 'normal', 'normal', 'attack', 'normal', 'normal', 'normal', 'normal', 'normal', 'attack', 'normal']
}

df = pd.DataFrame(data)
df

    src_port  dst_port protocol  packet_size_mean  packet_rate   label
0       8080        80      TCP               117         22.3  attack
1       3389      8080      UDP               598         28.7  normal
2         80        22      UDP               630         59.8  normal
3         21       443      UDP               389          3.1  normal
4         21        80      UDP               840         54.9  attack
5         21       443      UDP               282         55.5  normal
6        443      3389      TCP               507         11.8  normal
7         21       443      UDP               472          6.9  normal
8       3389      3389      TCP               730         18.9  normal
9         22        80      TCP               720         22.6  normal
10      8080       443      TCP               523         42.2  attack
11        80      8080      UDP               557         28.9  normal

### Ваше решение задачи 6

_Предложите новые признаки и добавьте их в DataFrame `df` в отдельной кодовой ячейке._

In [2]:
df = pd.DataFrame(data)
df['weak_ports'] = df['dst_port'].isin((80, 443))
df['volume'] = df['packet_size_mean'] * df['packet_rate']
df['anomaly'] = np.abs(df['packet_size_mean'] - df['packet_size_mean'].mean())
df

,src_port,dst_port,protocol,packet_size_mean,packet_rate,label,weak_ports,volume,anomaly
0,8080,80,TCP,117,22.3,attack,True,2609.1,413.416667
1,3389,8080,UDP,598,28.7,normal,False,17162.6,67.583333
2,80,22,UDP,630,59.8,normal,False,37674.0,99.583333
3,21,443,UDP,389,3.1,normal,True,1205.9,141.416667
4,21,80,UDP,840,54.9,attack,True,46116.0,309.583333
5,21,443,UDP,282,55.5,normal,True,15651.0,248.416667
6,443,3389,TCP,507,11.8,normal,False,5982.6,23.416667
7,21,443,UDP,472,6.9,normal,True,3256.8,58.416667
8,3389,3389,TCP,730,18.9,normal,False,13797.0,199.583333
9,22,80,TCP,720,22.6,normal,True,16272.0,189.583333
10,8080,443,TCP,523,42.2,attack,True,22070.6,7.416667
11,80,8080,UDP,557,28.9,normal,False,16097.3,26.583333

1. Если идет обращение к http/https, порты 80 и 443, вероятно атака
2. Больший объем передаваемых данных в секунду характерен для атак
3. Очень большие и очень маленькие пакеты данных, вероятно атаки